### ISSUE TITLE
[PE-D] Inability to find how to return to home after find command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-F09-1/tp#173]
Not able to return to home page after trying out find command due to home command being placed further below

![image.png](https://raw.githubusercontent.com/e0543403/ped/main/files/b3b8ff55-8c10-4393-9f84-d1464993fef4.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: e0543403/ped#2

**Comment by WangGLJoseph** [comment]
Will re-order the appearance of commands on the UG (put home and find commands together)
