### ISSUE TITLE
[PE-D] Possible to add assignment to module of no students

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-F09-1/tp#176]
![image.png](https://raw.githubusercontent.com/gycgabriel/ped/main/files/2681cc71-8ab1-4abc-abf8-f14b7c817a3e.png)

View cannot see added assignment if there are no students in the course when assignment is added

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: gycgabriel/ped#6

**Comment by WangGLJoseph** [comment]
Will make it clear in UG that it's possible to add tasks before students, but will not see the tasks since there are no students to display the tasks under.
