### ISSUE TITLE
[PE-D] Feature seems incomplete

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-F09-1/tp#181]
As a TA, I would probably want to see the list of students who haven't completed certain task for better student management. However, the way for me to do that currently seems to be looking at each student one by one. There is no feature for me to filter student list based on completion of certain task. Maybe this could be considered in future iterations.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: tianyue58/ped#12

**Comment by WangGLJoseph** [comment]
Will take into consideration as a future implementation
