### ISSUE TITLE
[PE-D] Lack of consolidated permitted characters for parameters in userguide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-F09-1/tp#186]
![image.png](https://raw.githubusercontent.com/e0543403/ped/main/files/07e08fbf-edd6-4f4f-a253-8b6d5efc0145.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: e0543403/ped#6

**Comment by WangGLJoseph** [comment]
Will create a section in the UG for consolidated permitted characters
