### ISSUE TITLE
[PE-D] Module's name is compared with itself during modification by edit module command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-F09-1/tp#189]
Technically this would not be possible.

![image.png](https://raw.githubusercontent.com/e0543403/ped/main/files/7538ba4a-118e-488b-9593-54c8079ff28f.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: e0543403/ped#7

**Comment by WangGLJoseph** [comment]
Separate error message when new mod name is same as old mod name
