### ISSUE TITLE
[PE-D] Delete Invalid Task Shows Success Message

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-F09-1/tp#190]
When deleting a non existent task, success message is shown when there should be another message about how the task is not found instead

delete task m/CS2103 ti/T99

![DeleteNonExistantTask.png](https://raw.githubusercontent.com/auhc99/ped/main/files/e8cab242-2156-4074-96e0-e53e600d060b.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: auhc99/ped#8

**Comment by WangGLJoseph** [comment]
Same as #166
