### ISSUE TITLE
[PE-D] Features not grouped together by relevance to each other

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-F09-1/tp#191]
Perhaps have all the module related features be grouped together followed by the student features, task features then find, home, clear and exit.

![image.png](https://raw.githubusercontent.com/e0543403/ped/main/files/cd988773-1581-4827-bee7-ac3e9359368d.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: e0543403/ped#8

**Comment by WangGLJoseph** [comment]
Related to #173
