### ISSUE TITLE
[PE-D] Permitted Characters for module names are not specified in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-F09-1/tp#194]
Permitted Characters for module names are not specified anywhere in the UG (Notes, add Module Command, edit Module Command ...)

They are only specified for Task Names. 

You can defined permitted characters under the Notes section

![permittedcharactersug.png](https://raw.githubusercontent.com/auhc99/ped/main/files/406934f0-71aa-4de4-8a87-caf64b29e095.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: auhc99/ped#11

**Comment by WangGLJoseph** [comment]
Same as #186
