### ISSUE TITLE
[PE-D] Words to be included in glossary 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-F09-1/tp#199]
The term “alphanumeric” can go into glossary as not all target users are expected to know the word’s meaning

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: tianyue58/ped#14

**Comment by WangGLJoseph** [comment]
Will specify the meaning of 'alphanumeric' as characters from [0-9][a-z][A-Z]

**Comment by WangGLJoseph** [comment]
Fixed in #214.
