### ISSUE TITLE
[PE-D] Typo in command summary

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-F09-1/tp#202]
This appears to be a typo in command summary.

![7B344353-670E-415C-90CF-22A1F185BE65.jpeg](https://raw.githubusercontent.com/tianyue58/ped/main/files/509287bf-cd2f-453a-9dd9-3151f13bfea7.jpeg)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: tianyue58/ped#17

**Comment by WangGLJoseph** [comment]
Fixed in #214.
