### ISSUE TITLE
Remove the module name parameter from edit student commands

### ISSUE THREAD

**Issue by WangGLJoseph** [AY2122S1-CS2103-F09-1/tp#216]
Since editing a student does so for all modules, should remove a redundant use of module name as a parameter in the edit student command.

**Comment by charliemoweng** [comment]
Agree. This falls under the Edit student part. I think can assign this issue to me.

**Comment by charliemoweng** [comment]
As this constitutes feature change, which is not allowed in v1.4, this suggestion will not be implemented in v1.4. Will stick to the original behaviour.
