### ISSUE TITLE
Branch naming convention

### ISSUE THREAD

**Issue by charliemoweng** [AY2122S1-CS2103-F09-1/tp#28]
I suggest that we can use `branch-<your name>-<the task this branch does>` as our branching convention. It follows our practice in the iP and is straightforward to anyone reviewing your PR.
Can close this issue once everyone agrees. Feel free to suggest otherwise.

**Comment by charliemoweng** [comment]
I agree.

**Comment by Ruofan1023** [comment]
Ok

**Comment by WangGLJoseph** [comment]
Agreed, thanks for the suggestion!

**Comment by tanjoewel** [comment]
Yup agreed

**Comment by charliemoweng** [comment]
All agreed. Will start using this convention for subsequent branches.
