### ISSUE TITLE
Procedure of reviewing and merging PRs

### ISSUE THREAD

**Issue by charliemoweng** [AY2122S1-CS2103-F09-1/tp#31]
my suggestion: two members other than the person who created the PR review the PR. 
the later one to review will merge the PR if no issues are found. 
if he/she realises something is not right, just write reviews or post a comment.
**TLDR: bottom line is 2 reviews from 2 people other than the creator of the PR before merging**

**Comment by charliemoweng** [comment]
I agree.

**Comment by WangGLJoseph** [comment]
Agreed.

**Comment by tanjoewel** [comment]
Yup agreed

**Comment by charliemoweng** [comment]
Another idea stems from a discussion with @WangGLJoseph about merging the PR. 
Since the 2nd person reviewing the PR will be in charge of merging it, he/she will see potential merge conflicts. 
And since he/she did not write these changes, it may be a hard time for him/her to resolve it. 

**2 ideas:**
1. After the 2nd person is done with reviewing, the creator of that PR initiates the merge and handles any potential conflicts.
2. The 2nd person still initiates the merge. He/she will only alert the creator of the PR when there is a conflict.

Please give your opinion on this.

**Comment by WangGLJoseph** [comment]
I agree with the 1st point, once the PR receives and passes 2 reviews, the creater of the PR should take care of the merging and resolving any conflicts.

**Comment by charliemoweng** [comment]
All agreed with the 1st point. For all subsequent PRs, at least 2 reviews from 2 people other than the creator of the PR will be required. The creator of the PR will then merge the PR.
